In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Data\syn_2021_HH.csv")

In [3]:
df = df[~(df["dwelltype"] == "Missing")]

column_mapping = {
    'totalvehs': 'TOTALVEHS',
    'hhsize': 'HHSIZE',
    'hhinc': 'INC'
}
df = df.rename(columns=column_mapping)

new_column_order = ['SA1', 'INC', 'TOTALVEHS', 'HHSIZE', 'dwelltype', 'owndwell']
df = df[new_column_order]
df.rename(columns={'SA1': 'SA1_CODE21'}, inplace=True)
df["SA1_CODE21"] = df["SA1_CODE21"].astype(str)

## One Hot Encoding

In [4]:
df_onehot = df.copy()
df_onehot = pd.get_dummies(df_onehot, columns=['dwelltype', 'owndwell'])
df_onehot

,SA1_CODE21,INC,TOTALVEHS,HHSIZE,dwelltype_Flat or Apartment,dwelltype_Other,dwelltype_Separate House,dwelltype_Terrace/Townhouse,owndwell_Being Purchased,owndwell_Being Rented,owndwell_Fully Owned,owndwell_Occupied Rent-Free,owndwell_Something Else
0,20302104732,350.0,1.0,3.0,0,0,1,0,1,0,0,0,0
1,20302104732,3600.0,0.0,2.0,0,0,1,0,0,0,1,0,0
2,20302104732,1900.0,1.0,2.0,0,0,1,0,0,0,1,0,0
3,20302104732,350.0,3.0,3.0,0,0,1,0,0,0,1,0,0
4,20302104732,800.0,2.0,2.0,0,0,1,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1902754,21402159223,2850.0,1.0,1.0,0,1,0,0,0,0,1,0,0
1902755,21402159223,3200.0,2.0,1.0,0,0,1,0,0,0,1,0,0
1902756,21402159223,2800.0,1.0,1.0,0,0,1,0,1,0,0,0,0
1902757,21402159223,3000.0,0.0,1.0,1,0,0,0,0,1,0,0,0
1902758,21402159223,700.0,1.0,1.0,0,0,1,0,0,0,1,0,0

In [14]:
df_onehot.to_csv('Data\clean_data.csv', index=False)